use_frameworks!

target 'Form_Example' do
  pod 'Form', :path => '../'
  pod "Pastel"
  pod 'ActiveLabel'
  pod 'TTTAttributedLabel'

  target 'Form_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
